/**
 * Phase 9 launch guards (no HTTP, no prisma CLI, no network):
 *
 *  1. Postgres schema drift alarm — the committed prisma/schema.postgres.prisma
 *     must equal the canonical transform of prisma/schema.prisma, byte for
 *     byte. The transform is re-implemented here on purpose (double-entry
 *     ledger): if the script AND the committed file drift together, this
 *     independent copy still catches it.
 *
 *  2. SEED_PROFILE=production branch of prisma/seed.ts — the production seed
 *     must create ONLY the SUPER_ADMIN bootstrap account (upserted, never
 *     wiping, never overwriting an already-rotated password) and none of the
 *     development fixtures (fake appointments in a real clinic queue are
 *     unacceptable).
 */
import { readFileSync } from 'fs';
import { join } from 'path';
import { compare } from 'bcryptjs';
import { db } from '@/lib/db';
import { isProductionSeed, seedProductionAdmin } from '../prisma/seed';

const PRISMA_DIR = join(__dirname, '..', 'prisma');
const SQLITE_SCHEMA = readFileSync(join(PRISMA_DIR, 'schema.prisma'), 'utf8');
const POSTGRES_SCHEMA = readFileSync(join(PRISMA_DIR, 'schema.postgres.prisma'), 'utf8');

const GENERATED_HEADER =
  '// GENERATED by scripts/sync-postgres-schema.mjs — do not hand-edit; models live in schema.prisma';

const DATASOURCE_RE = /datasource\s+\w+\s*\{[^}]*\}/;

/** Canonical transform — mirrors scripts/sync-postgres-schema.mjs in memory. */
function toPostgresInMemory(sqliteSource: string): string {
  const block = sqliteSource.match(DATASOURCE_RE);
  if (!block) throw new Error('test transform: datasource block not found in schema.prisma');
  const pgBlock = block[0]
    .replace(/provider\s*=\s*"[^"]*"/, 'provider = "postgresql"')
    .replace(/url\s*=\s*env\(\s*"DATABASE_URL"\s*\)/, (urlLine) => `${urlLine}\n  directUrl = env("DIRECT_URL")`);
  return `${GENERATED_HEADER}\n\n${sqliteSource.replace(DATASOURCE_RE, pgBlock)}`;
}

describe('schema.postgres.prisma drift alarm', () => {
  test('dev schema stays SQLite (premise of the dual-schema setup)', () => {
    const block = SQLITE_SCHEMA.match(DATASOURCE_RE);
    expect(block).not.toBeNull();
    expect(block![0]).toMatch(/provider\s*=\s*"sqlite"/);
  });

  test('committed Postgres copy matches the canonical transform BYTE FOR BYTE', () => {
    const expected = toPostgresInMemory(SQLITE_SCHEMA);
    // toBe gives a readable diff; Buffer.equals proves no invisible-char games.
    expect(POSTGRES_SCHEMA).toBe(expected);
    expect(Buffer.from(POSTGRES_SCHEMA, 'utf8').equals(Buffer.from(expected, 'utf8'))).toBe(true);
  });

  test('first line is the GENERATED header (do-not-hand-edit warning)', () => {
    expect(POSTGRES_SCHEMA.split('\n')[0]).toBe(GENERATED_HEADER);
  });

  test('datasource block: postgresql provider + directUrl, sqlite gone', () => {
    const block = POSTGRES_SCHEMA.match(DATASOURCE_RE);
    expect(block).not.toBeNull();
    expect(block![0]).toContain('provider = "postgresql"');
    expect(block![0]).toContain('directUrl = env("DIRECT_URL")');
    expect(block![0]).not.toContain('sqlite');
    expect(POSTGRES_SCHEMA).not.toContain('provider = "sqlite"');
  });

  test('models are untouched — same model count, no extra/missing model blocks', () => {
    const count = (s: string): number => (s.match(/^model\s+\w+\s*\{/gm) || []).length;
    expect(count(POSTGRES_SCHEMA)).toBe(count(SQLITE_SCHEMA));
    // spot canaries: every model name in schema.prisma survives verbatim
    for (const name of SQLITE_SCHEMA.matchAll(/^model\s+(\w+)\s*\{/gm)) {
      expect(POSTGRES_SCHEMA).toMatch(new RegExp(`^model\\s+${name[1]}\\s*\\{`, 'm'));
    }
  });
});

describe('SEED_PROFILE=production (seed.ts production branch)', () => {
  const ADMIN_PHONE = '+919999000001';

  describe('isProductionSeed guard', () => {
    test('true ONLY for the exact value "production"', () => {
      expect(isProductionSeed({ SEED_PROFILE: 'production' })).toBe(true);
      expect(isProductionSeed({})).toBe(false);
      expect(isProductionSeed({ SEED_PROFILE: 'development' })).toBe(false);
      expect(isProductionSeed({ SEED_PROFILE: 'Production' })).toBe(false); // case-sensitive
      expect(isProductionSeed({ SEED_PROFILE: '' })).toBe(false);
    });

    test('defaults to process.env — dev profile when unset', () => {
      const prev = process.env.SEED_PROFILE;
      delete process.env.SEED_PROFILE;
      expect(isProductionSeed()).toBe(false);
      process.env.SEED_PROFILE = 'production';
      expect(isProductionSeed()).toBe(true);
      if (prev === undefined) delete process.env.SEED_PROFILE;
      else process.env.SEED_PROFILE = prev;
    });
  });

  describe('seedProductionAdmin — SUPER_ADMIN only, zero fixtures', () => {
    beforeEach(async () => {
      await db.user.deleteMany({ where: { phone: ADMIN_PHONE } });
    });

    afterAll(async () => {
      // leave the shared test DB exactly as this suite found it
      await db.user.deleteMany({ where: { phone: ADMIN_PHONE } });
    });

    test('creates exactly one user and NO fixture rows', async () => {
      // The shared test DB accumulates fixtures from earlier suites — assert
      // DELTAS (exactly one row added, nothing else) instead of absolute zeros.
      const before = {
        users: await db.user.count(),
        doctors: await db.doctorProfile.count(),
        schedules: await db.schedule.count(),
        appointments: await db.appointment.count(),
        feedback: await db.feedback.count(),
        notes: await db.patientNote.count(),
        sessions: await db.session.count(),
        audit: await db.auditLog.count(),
      };

      await seedProductionAdmin(db);

      const admin = await db.user.findUnique({ where: { phone: ADMIN_PHONE } });
      expect(admin).not.toBeNull();
      expect(admin!.name).toBe('Platform Admin');
      expect(admin!.role).toBe('SUPER_ADMIN');
      expect(admin!.verificationStatus).toBe('VERIFIED');
      expect(admin!.mustChangePassword).toBe(false);
      expect(await compare('Test@1234', admin!.passwordHash)).toBe(true);

      // exactly ONE user added; every fixture table untouched
      expect(await db.user.count()).toBe(before.users + 1);
      expect(await db.doctorProfile.count()).toBe(before.doctors);
      expect(await db.schedule.count()).toBe(before.schedules);
      expect(await db.appointment.count()).toBe(before.appointments);
      expect(await db.feedback.count()).toBe(before.feedback);
      expect(await db.patientNote.count()).toBe(before.notes);
      expect(await db.session.count()).toBe(before.sessions);
      expect(await db.auditLog.count()).toBe(before.audit);
    });

    test('idempotent re-run: no duplicate row, never resets a rotated password', async () => {
      await seedProductionAdmin(db);
      // simulate the owner rotating the bootstrap password in production:
      await db.user.update({
        where: { phone: ADMIN_PHONE },
        data: { passwordHash: 'rotated-on-prod' },
      });

      await seedProductionAdmin(db); // upsert update:{} must not overwrite it

      const users = await db.user.findMany({ where: { phone: ADMIN_PHONE } });
      expect(users).toHaveLength(1);
      expect(users[0].passwordHash).toBe('rotated-on-prod');
    });
  });
});
